global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: relaypay-api
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]
  - job_name: relaypay-services
    metrics_path: /metrics
    static_configs:
      - targets:
          - "provider:8001"
          - "receiver:8002"
          - "bank:8003"
          - "commerce:8004"
  - job_name: relaypay-worker
    static_configs:
      - targets: ["worker:9100"]
