"""provider effects and faults

Revision ID: 0001_provider
Revises:
Create Date: 2026-07-16 18:25:56.128627
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001_provider"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provider_accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("signing_secret_digest", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "provider_effects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider_account_id", sa.Uuid(), nullable=False),
        sa.Column("stable_key", sa.String(length=128), nullable=False),
        sa.Column("operation_kind", sa.String(length=16), nullable=False),
        sa.Column("reference", sa.String(length=128), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("request_sha256", sa.LargeBinary(), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("decline_code", sa.String(length=64), nullable=True),
        sa.Column("response_bytes", sa.LargeBinary(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(outcome = 'DECLINED' AND decline_code IS NOT NULL) OR (outcome <> 'DECLINED' AND decline_code IS NULL)"
        ),
        sa.CheckConstraint(
            "(outcome = 'PENDING' AND completed_at IS NULL AND response_bytes IS NULL) OR (outcome IN ('SUCCEEDED', 'DECLINED') AND completed_at IS NOT NULL AND response_bytes IS NOT NULL)"
        ),
        sa.CheckConstraint("currency = 'INR'"),
        sa.CheckConstraint("operation_kind IN ('AUTHORIZE', 'CAPTURE', 'REFUND')"),
        sa.CheckConstraint("outcome IN ('PENDING', 'SUCCEEDED', 'DECLINED')"),
        sa.CheckConstraint("amount > 0"),
        sa.ForeignKeyConstraint(
            ["provider_account_id"],
            ["provider_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_account_id", "stable_key"),
    )
    op.create_index(
        "ix_provider_effects_stable_key",
        "provider_effects",
        ["provider_account_id", "stable_key"],
        unique=False,
    )
    op.create_table(
        "provider_fault_directives",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider_account_id", sa.Uuid(), nullable=False),
        sa.Column("stable_key", sa.String(length=128), nullable=False),
        sa.Column("fault_type", sa.String(length=24), nullable=False),
        sa.Column("remaining_uses", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "fault_type IN ('LOSE_RESPONSE', 'DECLINE', 'MALFORMED', 'UNSIGNED', 'MISMATCHED', 'PENDING')"
        ),
        sa.CheckConstraint("remaining_uses >= 0"),
        sa.ForeignKeyConstraint(
            ["provider_account_id"],
            ["provider_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_account_id", "stable_key", "fault_type"),
    )
    op.execute(
        """
        CREATE FUNCTION provider_prevent_effect_rebinding() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
          IF NEW.provider_account_id <> OLD.provider_account_id
            OR NEW.stable_key <> OLD.stable_key
            OR NEW.operation_kind <> OLD.operation_kind
            OR NEW.reference <> OLD.reference
            OR NEW.amount <> OLD.amount
            OR NEW.currency <> OLD.currency
            OR NEW.request_sha256 <> OLD.request_sha256 THEN
            RAISE EXCEPTION 'provider effect identity is immutable' USING ERRCODE = '55000';
          END IF;
          RETURN NEW;
        END;
        $$;
        CREATE TRIGGER provider_effect_identity_immutable
          BEFORE UPDATE ON provider_effects
          FOR EACH ROW EXECUTE FUNCTION provider_prevent_effect_rebinding();
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP FUNCTION IF EXISTS provider_prevent_effect_rebinding() CASCADE")
    op.drop_table("provider_fault_directives")
    op.drop_index("ix_provider_effects_stable_key", table_name="provider_effects")
    op.drop_table("provider_effects")
    op.drop_table("provider_accounts")
    # ### end Alembic commands ###
