"""payment operations and idempotency

Revision ID: 0002_payments
Revises: 0001_foundation
Create Date: 2026-07-16 18:23:27.075469
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002_payments"
down_revision: str | None = "0001_foundation"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provider_operations",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("payment_intent_id", sa.Uuid(), nullable=False),
        sa.Column("resource_type", sa.String(length=24), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("stable_provider_key", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("review_reason", sa.String(length=64), nullable=True),
        sa.Column("provider_request_bytes", sa.LargeBinary(), nullable=True),
        sa.Column("provider_request_sha256", sa.LargeBinary(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_lookup_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lookup_lease_token", sa.Uuid(), nullable=True),
        sa.Column("lookup_lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("apply_failure_count", sa.Integer(), nullable=False),
        sa.Column("terminal_http_status", sa.SmallInteger(), nullable=True),
        sa.Column(
            "terminal_response_headers", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("terminal_response_bytes", sa.LargeBinary(), nullable=True),
        sa.Column("terminal_response_sha256", sa.LargeBinary(), nullable=True),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status IN ('SUCCEEDED', 'FAILED') AND terminal_http_status IS NOT NULL AND terminal_response_bytes IS NOT NULL AND terminal_response_sha256 IS NOT NULL AND finalized_at IS NOT NULL) OR (status IN ('PROCESSING', 'REQUIRES_REVIEW') AND terminal_http_status IS NULL AND terminal_response_bytes IS NULL AND terminal_response_sha256 IS NULL AND finalized_at IS NULL)"
        ),
        sa.CheckConstraint("kind IN ('AUTHORIZE', 'CAPTURE', 'REFUND')"),
        sa.CheckConstraint("resource_type IN ('AUTHORIZATION', 'CAPTURE', 'REFUND')"),
        sa.CheckConstraint("status IN ('PROCESSING', 'SUCCEEDED', 'FAILED', 'REQUIRES_REVIEW')"),
        sa.CheckConstraint("apply_failure_count >= 0"),
        sa.CheckConstraint("attempt_count >= 0"),
        sa.CheckConstraint(
            "last_sent_at IS NULL OR (provider_request_bytes IS NOT NULL AND provider_request_sha256 IS NOT NULL AND attempt_count >= 1)"
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id", "payment_intent_id"],
            ["payment_intents.organisation_id", "payment_intents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organisation_id", "id"),
        sa.UniqueConstraint("organisation_id", "kind", "resource_id"),
        sa.UniqueConstraint("organisation_id", "stable_provider_key"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_index(
        "ix_provider_operations_lease_expiry",
        "provider_operations",
        ["lookup_lease_expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_provider_operations_recovery",
        "provider_operations",
        ["status", "next_lookup_at"],
        unique=False,
    )
    op.create_table(
        "authorizations",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("payment_intent_id", sa.Uuid(), nullable=False),
        sa.Column("provider_operation_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("failure_code", sa.String(length=64), nullable=True),
        sa.Column("authorized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'SUCCEEDED' AND authorized_at IS NOT NULL AND failure_code IS NULL) OR (status = 'FAILED' AND authorized_at IS NULL AND failure_code IS NOT NULL) OR (status IN ('PROCESSING', 'REQUIRES_REVIEW') AND authorized_at IS NULL)"
        ),
        sa.CheckConstraint("currency = 'INR'"),
        sa.CheckConstraint("status IN ('PROCESSING', 'SUCCEEDED', 'FAILED', 'REQUIRES_REVIEW')"),
        sa.CheckConstraint("amount > 0"),
        sa.ForeignKeyConstraint(
            ["organisation_id", "payment_intent_id"],
            ["payment_intents.organisation_id", "payment_intents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id", "provider_operation_id"],
            ["provider_operations.organisation_id", "provider_operations.id"],
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organisation_id", "id"),
        sa.UniqueConstraint("organisation_id", "payment_intent_id"),
        sa.UniqueConstraint("provider_operation_id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "idempotency_records",
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("key_digest", sa.LargeBinary(), nullable=False),
        sa.Column("key_hint", sa.String(length=32), nullable=True),
        sa.Column("fingerprint_sha256", sa.LargeBinary(), nullable=False),
        sa.Column("fingerprint_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("target_type", sa.String(length=24), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("provider_operation_id", sa.Uuid(), nullable=True),
        sa.Column("is_terminal", sa.Boolean(), nullable=False),
        sa.Column("http_status", sa.SmallInteger(), nullable=True),
        sa.Column("response_headers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("response_bytes", sa.LargeBinary(), nullable=True),
        sa.Column("response_sha256", sa.LargeBinary(), nullable=True),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("target_type IN ('PAYMENT_INTENT', 'PROVIDER_OPERATION')"),
        sa.CheckConstraint(
            "(is_terminal AND http_status IS NOT NULL AND response_bytes IS NOT NULL AND response_sha256 IS NOT NULL AND finalized_at IS NOT NULL) OR (NOT is_terminal AND provider_operation_id IS NOT NULL AND http_status IS NULL AND response_bytes IS NULL AND response_sha256 IS NULL AND finalized_at IS NULL)"
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id", "provider_operation_id"],
            ["provider_operations.organisation_id", "provider_operations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organisation_id", "key_digest"),
    )
    op.create_index(
        "ix_idempotency_operation_order",
        "idempotency_records",
        ["provider_operation_id", "id"],
        unique=False,
    )
    op.create_table(
        "provider_attempts",
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("provider_operation_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("attempt_kind", sa.String(length=16), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("request_sha256", sa.LargeBinary(), nullable=False),
        sa.Column("response_http_status", sa.SmallInteger(), nullable=True),
        sa.Column("response_bytes", sa.LargeBinary(), nullable=True),
        sa.Column("response_sha256", sa.LargeBinary(), nullable=True),
        sa.Column("provider_signature_valid", sa.Boolean(), nullable=True),
        sa.Column("classification", sa.String(length=64), nullable=True),
        sa.Column("safe_error_code", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("attempt_kind IN ('MUTATION', 'LOOKUP')"),
        sa.CheckConstraint(
            "state IN ('SENT', 'RESPONSE_RECEIVED', 'TRANSPORT_ERROR', 'VALIDATION_REJECTED')"
        ),
        sa.CheckConstraint("sequence > 0"),
        sa.ForeignKeyConstraint(
            ["organisation_id", "provider_operation_id"],
            ["provider_operations.organisation_id", "provider_operations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organisation_id", "id"),
        sa.UniqueConstraint("provider_operation_id", "sequence"),
    )
    op.create_index(
        "uq_provider_attempts_one_mutation",
        "provider_attempts",
        ["provider_operation_id"],
        unique=True,
        postgresql_where=sa.text("attempt_kind = 'MUTATION'"),
    )
    op.create_table(
        "captures",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("payment_intent_id", sa.Uuid(), nullable=False),
        sa.Column("authorization_id", sa.Uuid(), nullable=False),
        sa.Column("provider_operation_id", sa.Uuid(), nullable=False),
        sa.Column("journal_id", sa.Uuid(), nullable=True),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("failure_code", sa.String(length=64), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'SUCCEEDED' AND captured_at IS NOT NULL AND journal_id IS NOT NULL AND failure_code IS NULL) OR (status = 'FAILED' AND captured_at IS NULL AND journal_id IS NULL AND failure_code IS NOT NULL) OR (status IN ('PROCESSING', 'REQUIRES_REVIEW') AND captured_at IS NULL AND journal_id IS NULL)"
        ),
        sa.CheckConstraint("currency = 'INR'"),
        sa.CheckConstraint("status IN ('PROCESSING', 'SUCCEEDED', 'FAILED', 'REQUIRES_REVIEW')"),
        sa.CheckConstraint("amount > 0"),
        sa.ForeignKeyConstraint(
            ["organisation_id", "authorization_id"],
            ["authorizations.organisation_id", "authorizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id", "journal_id"],
            ["journals.organisation_id", "journals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id", "payment_intent_id"],
            ["payment_intents.organisation_id", "payment_intents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id", "provider_operation_id"],
            ["provider_operations.organisation_id", "provider_operations.id"],
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("journal_id"),
        sa.UniqueConstraint("organisation_id", "id"),
        sa.UniqueConstraint("organisation_id", "payment_intent_id"),
        sa.UniqueConstraint("provider_operation_id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "operation_history",
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("provider_operation_id", sa.Uuid(), nullable=False),
        sa.Column("from_status", sa.String(length=24), nullable=True),
        sa.Column("to_status", sa.String(length=24), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=False),
        sa.Column("evidence_attempt_id", sa.Uuid(), nullable=True),
        sa.Column("actor_type", sa.String(length=24), nullable=False),
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor_type IN ('REQUEST', 'RECOVERY_WORKER', 'ADMIN_LOOKUP', 'FINALIZER')"
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id", "evidence_attempt_id"],
            ["provider_attempts.organisation_id", "provider_attempts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id", "provider_operation_id"],
            ["provider_operations.organisation_id", "provider_operations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_operation_history_operation_created",
        "operation_history",
        ["provider_operation_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "refunds",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("payment_intent_id", sa.Uuid(), nullable=False),
        sa.Column("capture_id", sa.Uuid(), nullable=False),
        sa.Column("provider_operation_id", sa.Uuid(), nullable=False),
        sa.Column("journal_id", sa.Uuid(), nullable=True),
        sa.Column("merchant_refund_reference", sa.String(length=128), nullable=True),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("failure_code", sa.String(length=64), nullable=True),
        sa.Column("refunded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'SUCCEEDED' AND refunded_at IS NOT NULL AND journal_id IS NOT NULL AND failure_code IS NULL) OR (status = 'FAILED' AND refunded_at IS NULL AND journal_id IS NULL AND failure_code IS NOT NULL) OR (status IN ('PROCESSING', 'REQUIRES_REVIEW') AND refunded_at IS NULL AND journal_id IS NULL)"
        ),
        sa.CheckConstraint("currency = 'INR'"),
        sa.CheckConstraint("status IN ('PROCESSING', 'SUCCEEDED', 'FAILED', 'REQUIRES_REVIEW')"),
        sa.CheckConstraint("amount > 0"),
        sa.ForeignKeyConstraint(
            ["organisation_id", "capture_id"],
            ["captures.organisation_id", "captures.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id", "journal_id"],
            ["journals.organisation_id", "journals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id", "payment_intent_id"],
            ["payment_intents.organisation_id", "payment_intents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id", "provider_operation_id"],
            ["provider_operations.organisation_id", "provider_operations.id"],
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("journal_id"),
        sa.UniqueConstraint("organisation_id", "id"),
        sa.UniqueConstraint("provider_operation_id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_index(
        "ix_refunds_payment_status",
        "refunds",
        ["organisation_id", "payment_intent_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_refunds_merchant_reference",
        "refunds",
        ["organisation_id", "merchant_refund_reference"],
        unique=True,
        postgresql_where=sa.text("merchant_refund_reference IS NOT NULL"),
    )
    op.create_foreign_key(
        "fk_journals_provider_operation",
        "journals",
        "provider_operations",
        ["organisation_id", "provider_operation_id"],
        ["organisation_id", "id"],
    )
    op.execute(
        """
        CREATE FUNCTION relaypay_guard_provider_attempt_update() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
          IF NEW.organisation_id <> OLD.organisation_id
            OR NEW.provider_operation_id <> OLD.provider_operation_id
            OR NEW.sequence <> OLD.sequence
            OR NEW.attempt_kind <> OLD.attempt_kind
            OR NEW.request_sha256 <> OLD.request_sha256
            OR NEW.started_at <> OLD.started_at
            OR OLD.completed_at IS NOT NULL
            OR OLD.state <> 'SENT'
            OR NEW.state = 'SENT'
            OR NEW.completed_at IS NULL THEN
            RAISE EXCEPTION 'provider attempt history is immutable after completion'
              USING ERRCODE = '55000';
          END IF;
          RETURN NEW;
        END;
        $$;
        CREATE TRIGGER provider_attempts_one_way_completion
          BEFORE UPDATE ON provider_attempts
          FOR EACH ROW EXECUTE FUNCTION relaypay_guard_provider_attempt_update();
        CREATE TRIGGER provider_attempts_no_delete
          BEFORE DELETE ON provider_attempts
          FOR EACH ROW EXECUTE FUNCTION relaypay_prevent_evidence_mutation();
        CREATE TRIGGER operation_history_immutable
          BEFORE UPDATE OR DELETE ON operation_history
          FOR EACH ROW EXECUTE FUNCTION relaypay_prevent_evidence_mutation();

        CREATE FUNCTION relaypay_validate_provider_operation_resource() RETURNS trigger
        LANGUAGE plpgsql AS $$
        DECLARE
          resource_exists boolean;
        BEGIN
          IF NEW.resource_type = 'AUTHORIZATION' AND NEW.kind = 'AUTHORIZE' THEN
            SELECT EXISTS (
              SELECT 1 FROM authorizations r
              WHERE r.id = NEW.resource_id
                AND r.organisation_id = NEW.organisation_id
                AND r.payment_intent_id = NEW.payment_intent_id
                AND r.provider_operation_id = NEW.id
            ) INTO resource_exists;
          ELSIF NEW.resource_type = 'CAPTURE' AND NEW.kind = 'CAPTURE' THEN
            SELECT EXISTS (
              SELECT 1 FROM captures r
              WHERE r.id = NEW.resource_id
                AND r.organisation_id = NEW.organisation_id
                AND r.payment_intent_id = NEW.payment_intent_id
                AND r.provider_operation_id = NEW.id
            ) INTO resource_exists;
          ELSIF NEW.resource_type = 'REFUND' AND NEW.kind = 'REFUND' THEN
            SELECT EXISTS (
              SELECT 1 FROM refunds r
              WHERE r.id = NEW.resource_id
                AND r.organisation_id = NEW.organisation_id
                AND r.payment_intent_id = NEW.payment_intent_id
                AND r.provider_operation_id = NEW.id
            ) INTO resource_exists;
          ELSE
            resource_exists := false;
          END IF;

          IF NOT resource_exists THEN
            RAISE EXCEPTION 'provider operation % resource binding is invalid', NEW.id
              USING ERRCODE = '23514';
          END IF;
          RETURN NULL;
        END;
        $$;

        CREATE CONSTRAINT TRIGGER provider_operation_resource_at_commit
          AFTER INSERT OR UPDATE ON provider_operations DEFERRABLE INITIALLY DEFERRED
          FOR EACH ROW EXECUTE FUNCTION relaypay_validate_provider_operation_resource();

        CREATE FUNCTION relaypay_validate_capture_command() RETURNS trigger
        LANGUAGE plpgsql AS $$
        DECLARE
          payment_amount bigint;
          authorization_status text;
        BEGIN
          SELECT amount INTO payment_amount FROM payment_intents
            WHERE id = NEW.payment_intent_id AND organisation_id = NEW.organisation_id;
          SELECT status INTO authorization_status FROM authorizations
            WHERE id = NEW.authorization_id AND organisation_id = NEW.organisation_id;
          IF NEW.amount <> payment_amount THEN
            RAISE EXCEPTION 'capture % must equal the full payment amount', NEW.id
              USING ERRCODE = '23514';
          END IF;
          IF authorization_status <> 'SUCCEEDED' THEN
            RAISE EXCEPTION 'capture % requires a succeeded authorization', NEW.id
              USING ERRCODE = '23514';
          END IF;
          RETURN NULL;
        END;
        $$;

        CREATE CONSTRAINT TRIGGER capture_command_at_commit
          AFTER INSERT OR UPDATE ON captures DEFERRABLE INITIALLY DEFERRED
          FOR EACH ROW EXECUTE FUNCTION relaypay_validate_capture_command();

        CREATE FUNCTION relaypay_validate_refund_reservations() RETURNS trigger
        LANGUAGE plpgsql AS $$
        DECLARE
          capture_amount bigint;
          capture_status text;
          reserved_amount bigint;
        BEGIN
          SELECT amount, status INTO capture_amount, capture_status FROM captures
            WHERE id = NEW.capture_id AND organisation_id = NEW.organisation_id;
          IF capture_status <> 'SUCCEEDED' THEN
            RAISE EXCEPTION 'refund % requires a succeeded capture', NEW.id
              USING ERRCODE = '23514';
          END IF;
          SELECT COALESCE(sum(amount), 0) INTO reserved_amount FROM refunds
            WHERE payment_intent_id = NEW.payment_intent_id
              AND organisation_id = NEW.organisation_id
              AND status IN ('PROCESSING', 'REQUIRES_REVIEW', 'SUCCEEDED');
          IF reserved_amount > capture_amount THEN
            RAISE EXCEPTION 'refund reservations exceed captured amount for payment %',
              NEW.payment_intent_id USING ERRCODE = '23514';
          END IF;
          RETURN NULL;
        END;
        $$;

        CREATE CONSTRAINT TRIGGER refund_reservations_at_commit
          AFTER INSERT OR UPDATE ON refunds DEFERRABLE INITIALLY DEFERRED
          FOR EACH ROW EXECUTE FUNCTION relaypay_validate_refund_reservations();

        CREATE FUNCTION relaypay_validate_idempotency_target() RETURNS trigger
        LANGUAGE plpgsql AS $$
        DECLARE
          target_exists boolean;
        BEGIN
          IF NEW.target_type = 'PAYMENT_INTENT' THEN
            SELECT EXISTS (
              SELECT 1 FROM payment_intents p
              WHERE p.id = NEW.target_id AND p.organisation_id = NEW.organisation_id
            ) INTO target_exists;
            target_exists := target_exists AND NEW.is_terminal AND NEW.provider_operation_id IS NULL;
          ELSIF NEW.target_type = 'PROVIDER_OPERATION' THEN
            SELECT EXISTS (
              SELECT 1 FROM provider_operations o
              WHERE o.id = NEW.target_id
                AND o.id = NEW.provider_operation_id
                AND o.organisation_id = NEW.organisation_id
            ) INTO target_exists;
          ELSE
            target_exists := false;
          END IF;
          IF NOT target_exists THEN
            RAISE EXCEPTION 'idempotency record % target binding is invalid', NEW.id
              USING ERRCODE = '23514';
          END IF;
          RETURN NULL;
        END;
        $$;

        CREATE CONSTRAINT TRIGGER idempotency_target_at_commit
          AFTER INSERT OR UPDATE ON idempotency_records DEFERRABLE INITIALLY DEFERRED
          FOR EACH ROW EXECUTE FUNCTION relaypay_validate_idempotency_target();

        CREATE FUNCTION relaypay_validate_journal_operation() RETURNS trigger
        LANGUAGE plpgsql AS $$
        DECLARE
          operation_kind text;
          operation_resource_id uuid;
          operation_organisation_id uuid;
          expected_amount bigint;
          journal_debit_total bigint;
        BEGIN
          IF NEW.journal_type = 'COMPENSATION' THEN
            RETURN NULL;
          END IF;
          SELECT kind, resource_id, organisation_id
            INTO operation_kind, operation_resource_id, operation_organisation_id
            FROM provider_operations WHERE id = NEW.provider_operation_id;
          IF operation_kind <> NEW.journal_type
            OR operation_resource_id <> NEW.reference_id
            OR operation_organisation_id <> NEW.organisation_id THEN
            RAISE EXCEPTION 'journal % provider operation binding is invalid', NEW.id
              USING ERRCODE = '23514';
          END IF;
          IF NEW.journal_type = 'CAPTURE' THEN
            SELECT amount INTO expected_amount FROM captures WHERE id = NEW.reference_id;
          ELSE
            SELECT amount INTO expected_amount FROM refunds WHERE id = NEW.reference_id;
          END IF;
          SELECT COALESCE(sum(amount) FILTER (WHERE side = 'DEBIT'), 0)
            INTO journal_debit_total FROM postings WHERE journal_id = NEW.id;
          IF journal_debit_total <> expected_amount THEN
            RAISE EXCEPTION 'journal % amount does not match its financial resource', NEW.id
              USING ERRCODE = '23514';
          END IF;
          RETURN NULL;
        END;
        $$;

        CREATE CONSTRAINT TRIGGER journal_operation_at_commit
          AFTER INSERT ON journals DEFERRABLE INITIALLY DEFERRED
          FOR EACH ROW EXECUTE FUNCTION relaypay_validate_journal_operation();
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP FUNCTION IF EXISTS relaypay_validate_journal_operation() CASCADE")
    op.execute("DROP FUNCTION IF EXISTS relaypay_guard_provider_attempt_update() CASCADE")
    op.execute("DROP FUNCTION IF EXISTS relaypay_validate_idempotency_target() CASCADE")
    op.execute("DROP FUNCTION IF EXISTS relaypay_validate_refund_reservations() CASCADE")
    op.execute("DROP FUNCTION IF EXISTS relaypay_validate_capture_command() CASCADE")
    op.execute("DROP FUNCTION IF EXISTS relaypay_validate_provider_operation_resource() CASCADE")
    op.drop_constraint("fk_journals_provider_operation", "journals", type_="foreignkey")
    op.drop_index(
        "uq_refunds_merchant_reference",
        table_name="refunds",
        postgresql_where=sa.text("merchant_refund_reference IS NOT NULL"),
    )
    op.drop_index("ix_refunds_payment_status", table_name="refunds")
    op.drop_table("refunds")
    op.drop_index("ix_operation_history_operation_created", table_name="operation_history")
    op.drop_table("operation_history")
    op.drop_table("captures")
    op.drop_index(
        "uq_provider_attempts_one_mutation",
        table_name="provider_attempts",
        postgresql_where=sa.text("attempt_kind = 'MUTATION'"),
    )
    op.drop_table("provider_attempts")
    op.drop_index("ix_idempotency_operation_order", table_name="idempotency_records")
    op.drop_table("idempotency_records")
    op.drop_table("authorizations")
    op.drop_index("ix_provider_operations_recovery", table_name="provider_operations")
    op.drop_index("ix_provider_operations_lease_expiry", table_name="provider_operations")
    op.drop_table("provider_operations")
    # ### end Alembic commands ###
