"""versioned connectors and inbound webhook evidence

Revision ID: 0011_connectors
Revises: 0010_payouts
Create Date: 2026-07-30 18:33:55.064976
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0011_connectors"
down_revision: str | None = "0010_payouts"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connectors",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("reference", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("circuit_state", sa.String(length=16), nullable=False),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("circuit_state IN ('CLOSED', 'OPEN', 'HALF_OPEN')"),
        sa.CheckConstraint("kind IN ('PAYMENT', 'BANK', 'COMMERCE')"),
        sa.CheckConstraint("status IN ('ACTIVE', 'DISABLED')"),
        sa.ForeignKeyConstraint(
            ["organisation_id", "environment_id"],
            ["environments.organisation_id", "environments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organisation_id", "environment_id", "id"),
        sa.UniqueConstraint("organisation_id", "environment_id", "reference"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "connector_health_observations",
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("connector_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("error_category", sa.String(length=16), nullable=True),
        sa.Column("safe_error_code", sa.String(length=64), nullable=True),
        sa.Column("provider_rate_limit_remaining", sa.Integer(), nullable=True),
        sa.Column("provider_retry_after_seconds", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "error_category IS NULL OR error_category IN ('TEMPORARY', 'PERMANENT', 'AMBIGUOUS', 'RATE_LIMITED')"
        ),
        sa.CheckConstraint("status IN ('HEALTHY', 'DEGRADED', 'UNAVAILABLE')"),
        sa.ForeignKeyConstraint(
            ["organisation_id", "environment_id", "connector_id"],
            ["connectors.organisation_id", "connectors.environment_id", "connectors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organisation_id", "environment_id", "id"),
    )
    op.create_table(
        "connector_versions",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("connector_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("base_url", sa.String(length=512), nullable=False),
        sa.Column("capabilities", sa.String(length=256), nullable=False),
        sa.Column("timeout_ms", sa.Integer(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('PENDING', 'ACTIVE', 'REVOKED')"),
        sa.CheckConstraint("timeout_ms BETWEEN 100 AND 30000"),
        sa.CheckConstraint("version > 0"),
        sa.ForeignKeyConstraint(
            ["organisation_id", "environment_id", "connector_id"],
            ["connectors.organisation_id", "connectors.environment_id", "connectors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("connector_id", "version"),
        sa.UniqueConstraint("organisation_id", "environment_id", "id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "inbound_webhook_events",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("connector_id", sa.Uuid(), nullable=False),
        sa.Column("provider_event_id", sa.String(length=128), nullable=False),
        sa.Column("signature_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_bytes", sa.LargeBinary(), nullable=False),
        sa.Column("payload_sha256", sa.LargeBinary(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dead_lettered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('PENDING', 'PROCESSING', 'PROCESSED', 'DEAD_LETTER')"),
        sa.CheckConstraint("octet_length(payload_sha256) = 32"),
        sa.ForeignKeyConstraint(
            ["organisation_id", "environment_id", "connector_id"],
            ["connectors.organisation_id", "connectors.environment_id", "connectors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("connector_id", "provider_event_id"),
        sa.UniqueConstraint("organisation_id", "environment_id", "id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_index(
        "ix_inbound_webhook_claim",
        "inbound_webhook_events",
        ["status", "next_attempt_at"],
        unique=False,
    )
    op.create_table(
        "connector_credential_versions",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("connector_version_id", sa.Uuid(), nullable=False),
        sa.Column("credential_name", sa.String(length=64), nullable=False),
        sa.Column("encrypted_secret", sa.LargeBinary(), nullable=False),
        sa.Column("secret_sha256", sa.LargeBinary(), nullable=False),
        sa.Column("key_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("octet_length(secret_sha256) = 32"),
        sa.ForeignKeyConstraint(
            ["organisation_id", "environment_id", "connector_version_id"],
            [
                "connector_versions.organisation_id",
                "connector_versions.environment_id",
                "connector_versions.id",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("connector_version_id", "credential_name"),
        sa.UniqueConstraint("organisation_id", "environment_id", "id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "inbound_webhook_attempts",
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("inbound_webhook_event_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("safe_error_code", sa.String(length=64), nullable=True),
        sa.Column("processing_ms", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("outcome IN ('PROCESSED', 'RETRY', 'DEAD_LETTER')"),
        sa.CheckConstraint("attempt_number > 0"),
        sa.ForeignKeyConstraint(
            ["organisation_id", "environment_id", "inbound_webhook_event_id"],
            [
                "inbound_webhook_events.organisation_id",
                "inbound_webhook_events.environment_id",
                "inbound_webhook_events.id",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("inbound_webhook_event_id", "attempt_number"),
        sa.UniqueConstraint("organisation_id", "environment_id", "id"),
    )
    op.execute(
        """
        CREATE TRIGGER connector_credentials_immutable
          BEFORE UPDATE OR DELETE ON connector_credential_versions
          FOR EACH ROW EXECUTE FUNCTION relaypay_prevent_balance_evidence_mutation();
        CREATE TRIGGER connector_health_immutable
          BEFORE UPDATE OR DELETE ON connector_health_observations
          FOR EACH ROW EXECUTE FUNCTION relaypay_prevent_balance_evidence_mutation();
        CREATE TRIGGER inbound_attempts_immutable
          BEFORE UPDATE OR DELETE ON inbound_webhook_attempts
          FOR EACH ROW EXECUTE FUNCTION relaypay_prevent_balance_evidence_mutation();
        CREATE FUNCTION relaypay_prevent_inbound_payload_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF NEW.payload_bytes IS DISTINCT FROM OLD.payload_bytes
             OR NEW.payload_sha256 IS DISTINCT FROM OLD.payload_sha256
             OR NEW.provider_event_id IS DISTINCT FROM OLD.provider_event_id
             OR NEW.signature_timestamp IS DISTINCT FROM OLD.signature_timestamp THEN
            RAISE EXCEPTION 'inbound webhook source evidence is immutable';
          END IF;
          RETURN NEW;
        END;
        $$;
        CREATE TRIGGER inbound_payload_immutable
          BEFORE UPDATE ON inbound_webhook_events
          FOR EACH ROW EXECUTE FUNCTION relaypay_prevent_inbound_payload_mutation();
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP FUNCTION relaypay_prevent_inbound_payload_mutation() CASCADE")
    op.drop_table("inbound_webhook_attempts")
    op.drop_table("connector_credential_versions")
    op.drop_index("ix_inbound_webhook_claim", table_name="inbound_webhook_events")
    op.drop_table("inbound_webhook_events")
    op.drop_table("connector_versions")
    op.drop_table("connector_health_observations")
    op.drop_table("connectors")
    # ### end Alembic commands ###
