"""immutable dispute cases packages and submissions

Revision ID: 0014_disputes
Revises: 0013_agent_runtime
Create Date: 2026-08-08 18:29:09.159334
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0014_disputes"
down_revision: str | None = "0013_agent_runtime"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dispute_cases",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("payment_intent_id", sa.Uuid(), nullable=False),
        sa.Column("workflow_run_id", sa.Uuid(), nullable=True),
        sa.Column("network_dispute_id", sa.String(length=128), nullable=False),
        sa.Column("reason_code", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_sha256", sa.LargeBinary(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0 AND currency = 'INR'"),
        sa.CheckConstraint(
            "reason_code IN ('FRAUD', 'PRODUCT_NOT_RECEIVED', 'NOT_AS_DESCRIBED', 'DUPLICATE', 'CREDIT_NOT_PROCESSED', 'OTHER')"
        ),
        sa.CheckConstraint(
            "status IN ('OPEN', 'DRAFTED', 'WAITING_FOR_APPROVAL', 'APPROVED', 'SUBMITTING', 'SUBMITTED', 'REQUIRES_REVIEW')"
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id", "environment_id"],
            ["environments.organisation_id", "environments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_intent_id"],
            ["payment_intents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organisation_id", "environment_id", "network_dispute_id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_index(
        "ix_dispute_cases_scope_created",
        "dispute_cases",
        ["organisation_id", "environment_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "dispute_draft_versions",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("dispute_case_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("author_type", sa.String(length=16), nullable=False),
        sa.Column("author_user_id", sa.Uuid(), nullable=True),
        sa.Column("classification", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("response_text", sa.Text(), nullable=False),
        sa.Column("selected_evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("missing_evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_sha256", sa.LargeBinary(), nullable=False),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("author_type IN ('AGENT', 'ANALYST')"),
        sa.CheckConstraint("confidence IN ('LOW', 'MEDIUM', 'HIGH')"),
        sa.CheckConstraint("version > 0"),
        sa.ForeignKeyConstraint(
            ["dispute_case_id"],
            ["dispute_cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id", "environment_id"],
            ["environments.organisation_id", "environments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dispute_case_id", "version"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "dispute_package_versions",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("dispute_case_id", sa.Uuid(), nullable=False),
        sa.Column("draft_version_id", sa.Uuid(), nullable=False),
        sa.Column("workflow_artifact_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("package_sha256", sa.LargeBinary(), nullable=False),
        sa.Column("byte_length", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('FROZEN', 'APPROVED', 'INVALIDATED', 'SUBMITTED')"),
        sa.CheckConstraint("version > 0 AND byte_length BETWEEN 0 AND 20971520"),
        sa.ForeignKeyConstraint(
            ["dispute_case_id"],
            ["dispute_cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["draft_version_id"],
            ["dispute_draft_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id", "environment_id"],
            ["environments.organisation_id", "environments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_artifact_id"],
            ["workflow_artifacts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dispute_case_id", "version"),
        sa.UniqueConstraint("package_sha256"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "dispute_submission_attempts",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("dispute_case_id", sa.Uuid(), nullable=False),
        sa.Column("package_version_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("stable_key", sa.String(length=192), nullable=False),
        sa.Column("request_sha256", sa.LargeBinary(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("response_code", sa.String(length=64), nullable=True),
        sa.Column("response_sha256", sa.LargeBinary(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('SENT', 'AMBIGUOUS', 'SUCCEEDED', 'FAILED')"),
        sa.CheckConstraint("attempt_number > 0"),
        sa.ForeignKeyConstraint(
            ["dispute_case_id"],
            ["dispute_cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id", "environment_id"],
            ["environments.organisation_id", "environments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["package_version_id"],
            ["dispute_package_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dispute_case_id", "attempt_number"),
        sa.UniqueConstraint("public_id"),
        sa.UniqueConstraint("stable_key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dispute_submission_attempts")
    op.drop_table("dispute_package_versions")
    op.drop_table("dispute_draft_versions")
    op.drop_index("ix_dispute_cases_scope_created", table_name="dispute_cases")
    op.drop_table("dispute_cases")
    # ### end Alembic commands ###
