"""webhook endpoint versions recipients and deliveries

Revision ID: 0004_delivery
Revises: 0003_events
Create Date: 2026-07-17 10:29:54.772359
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004_delivery"
down_revision: str | None = "0003_events"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webhook_endpoints",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('ACTIVE', 'DISABLED')"),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organisation_id", "id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "webhook_endpoint_versions",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("webhook_endpoint_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=False),
        sa.Column("encrypted_secret", sa.LargeBinary(), nullable=False),
        sa.Column("subscribed_event_types", sa.ARRAY(sa.String(length=64)), nullable=False),
        sa.Column("active_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("active_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "subscribed_event_types <@ ARRAY['payment.authorized.v1', 'payment.captured.v1', 'refund.succeeded.v1']::varchar[]"
        ),
        sa.CheckConstraint("active_until IS NULL OR active_until > active_from"),
        sa.CheckConstraint("cardinality(subscribed_event_types) > 0"),
        sa.CheckConstraint("version > 0"),
        sa.ForeignKeyConstraint(
            ["organisation_id", "webhook_endpoint_id"],
            ["webhook_endpoints.organisation_id", "webhook_endpoints.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organisation_id", "id"),
        sa.UniqueConstraint("public_id"),
        sa.UniqueConstraint("webhook_endpoint_id", "version"),
    )
    op.create_table(
        "event_recipients",
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("merchant_event_id", sa.Uuid(), nullable=False),
        sa.Column("endpoint_version_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id", "endpoint_version_id"],
            ["webhook_endpoint_versions.organisation_id", "webhook_endpoint_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id", "merchant_event_id"],
            ["merchant_events.organisation_id", "merchant_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("merchant_event_id", "endpoint_version_id"),
        sa.UniqueConstraint("organisation_id", "id"),
    )
    op.create_index(
        "ix_event_recipients_event_order",
        "event_recipients",
        ["merchant_event_id", "id"],
        unique=False,
    )
    op.create_table(
        "webhook_deliveries",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("event_recipient_id", sa.Uuid(), nullable=False),
        sa.Column("replay_of_delivery_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dead_lettered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status IN ('PENDING', 'RETRY_WAIT') AND lease_token IS NULL AND lease_expires_at IS NULL AND delivered_at IS NULL AND dead_lettered_at IS NULL) OR (status = 'DELIVERING' AND lease_token IS NOT NULL AND lease_expires_at IS NOT NULL AND delivered_at IS NULL AND dead_lettered_at IS NULL) OR (status = 'DELIVERED' AND lease_token IS NULL AND lease_expires_at IS NULL AND delivered_at IS NOT NULL AND dead_lettered_at IS NULL) OR (status = 'DEAD_LETTER' AND lease_token IS NULL AND lease_expires_at IS NULL AND delivered_at IS NULL AND dead_lettered_at IS NOT NULL)"
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'DELIVERING', 'RETRY_WAIT', 'DELIVERED', 'DEAD_LETTER')"
        ),
        sa.CheckConstraint("attempt_count >= 0"),
        sa.ForeignKeyConstraint(
            ["organisation_id", "event_recipient_id"],
            ["event_recipients.organisation_id", "event_recipients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id", "replay_of_delivery_id"],
            ["webhook_deliveries.organisation_id", "webhook_deliveries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organisation_id", "id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_index(
        "ix_webhook_deliveries_claim",
        "webhook_deliveries",
        ["status", "next_attempt_at"],
        unique=False,
    )
    op.create_index(
        "ix_webhook_deliveries_expired_lease",
        "webhook_deliveries",
        ["lease_expires_at"],
        unique=False,
        postgresql_where=sa.text("status = 'DELIVERING'"),
    )
    op.create_index(
        "uq_webhook_deliveries_initial_recipient",
        "webhook_deliveries",
        ["event_recipient_id"],
        unique=True,
        postgresql_where=sa.text("replay_of_delivery_id IS NULL"),
    )
    op.create_table(
        "webhook_delivery_attempts",
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("webhook_delivery_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("lease_token", sa.Uuid(), nullable=False),
        sa.Column("request_timestamp", sa.BigInteger(), nullable=False),
        sa.Column("event_sha256", sa.LargeBinary(), nullable=False),
        sa.Column("response_http_status", sa.SmallInteger(), nullable=True),
        sa.Column("result", sa.String(length=24), nullable=False),
        sa.Column("safe_error_code", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(result = 'TRANSPORT_ERROR' AND response_http_status IS NULL) OR (result <> 'TRANSPORT_ERROR' AND response_http_status IS NOT NULL)"
        ),
        sa.CheckConstraint(
            "result IN ('ACKNOWLEDGED', 'RETRYABLE', 'PERMANENT', 'TRANSPORT_ERROR')"
        ),
        sa.CheckConstraint("sequence > 0"),
        sa.ForeignKeyConstraint(
            ["organisation_id", "webhook_delivery_id"],
            ["webhook_deliveries.organisation_id", "webhook_deliveries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("webhook_delivery_id", "sequence"),
    )
    op.create_index(
        "ix_webhook_delivery_attempts_delivery_order",
        "webhook_delivery_attempts",
        ["webhook_delivery_id", "sequence"],
        unique=False,
    )
    op.execute(
        """
        CREATE FUNCTION relaypay_guard_endpoint_version_update() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
          IF (to_jsonb(NEW) - 'active_until') <> (to_jsonb(OLD) - 'active_until')
            OR OLD.active_until IS NOT NULL
            OR NEW.active_until IS NULL
            OR NEW.active_until <= NEW.active_from THEN
            RAISE EXCEPTION 'webhook endpoint versions are immutable except for one-way closure'
              USING ERRCODE = '55000';
          END IF;
          RETURN NEW;
        END;
        $$;
        CREATE TRIGGER webhook_endpoint_versions_one_way_closure
          BEFORE UPDATE ON webhook_endpoint_versions
          FOR EACH ROW EXECUTE FUNCTION relaypay_guard_endpoint_version_update();
        CREATE TRIGGER webhook_endpoint_versions_no_delete
          BEFORE DELETE ON webhook_endpoint_versions
          FOR EACH ROW EXECUTE FUNCTION relaypay_prevent_evidence_mutation();
        CREATE TRIGGER event_recipients_immutable
          BEFORE UPDATE OR DELETE ON event_recipients
          FOR EACH ROW EXECUTE FUNCTION relaypay_prevent_evidence_mutation();
        CREATE TRIGGER webhook_delivery_attempts_immutable
          BEFORE UPDATE OR DELETE ON webhook_delivery_attempts
          FOR EACH ROW EXECUTE FUNCTION relaypay_prevent_evidence_mutation();

        CREATE FUNCTION relaypay_validate_delivery_attempt() RETURNS trigger
        LANGUAGE plpgsql AS $$
        DECLARE
          delivery_status text;
          delivery_lease uuid;
          stored_event_sha bytea;
        BEGIN
          SELECT d.status, d.lease_token, e.event_sha256
            INTO delivery_status, delivery_lease, stored_event_sha
            FROM webhook_deliveries d
            JOIN event_recipients r ON r.id = d.event_recipient_id
            JOIN merchant_events e ON e.id = r.merchant_event_id
            WHERE d.id = NEW.webhook_delivery_id
              AND d.organisation_id = NEW.organisation_id;
          IF delivery_status <> 'DELIVERING'
            OR delivery_lease <> NEW.lease_token
            OR stored_event_sha <> NEW.event_sha256 THEN
            RAISE EXCEPTION 'delivery attempt is not bound to the active lease and event bytes'
              USING ERRCODE = '23514';
          END IF;
          RETURN NEW;
        END;
        $$;
        CREATE TRIGGER webhook_delivery_attempt_binding
          BEFORE INSERT ON webhook_delivery_attempts
          FOR EACH ROW EXECUTE FUNCTION relaypay_validate_delivery_attempt();

        CREATE FUNCTION relaypay_validate_delivery_replay() RETURNS trigger
        LANGUAGE plpgsql AS $$
        DECLARE
          original_recipient uuid;
        BEGIN
          IF NEW.replay_of_delivery_id IS NULL THEN
            RETURN NEW;
          END IF;
          IF NEW.replay_of_delivery_id = NEW.id THEN
            RAISE EXCEPTION 'delivery cannot replay itself' USING ERRCODE = '23514';
          END IF;
          SELECT event_recipient_id INTO original_recipient
            FROM webhook_deliveries
            WHERE id = NEW.replay_of_delivery_id
              AND organisation_id = NEW.organisation_id;
          IF original_recipient IS NULL OR original_recipient <> NEW.event_recipient_id THEN
            RAISE EXCEPTION 'delivery replay must preserve its original recipient'
              USING ERRCODE = '23514';
          END IF;
          RETURN NEW;
        END;
        $$;
        CREATE TRIGGER webhook_delivery_replay_binding
          BEFORE INSERT OR UPDATE OF replay_of_delivery_id, event_recipient_id
          ON webhook_deliveries
          FOR EACH ROW EXECUTE FUNCTION relaypay_validate_delivery_replay();
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP FUNCTION IF EXISTS relaypay_validate_delivery_replay() CASCADE")
    op.execute("DROP FUNCTION IF EXISTS relaypay_validate_delivery_attempt() CASCADE")
    op.execute("DROP FUNCTION IF EXISTS relaypay_guard_endpoint_version_update() CASCADE")
    op.drop_index(
        "ix_webhook_delivery_attempts_delivery_order", table_name="webhook_delivery_attempts"
    )
    op.drop_table("webhook_delivery_attempts")
    op.drop_index(
        "uq_webhook_deliveries_initial_recipient",
        table_name="webhook_deliveries",
        postgresql_where=sa.text("replay_of_delivery_id IS NULL"),
    )
    op.drop_index(
        "ix_webhook_deliveries_expired_lease",
        table_name="webhook_deliveries",
        postgresql_where=sa.text("status = 'DELIVERING'"),
    )
    op.drop_index("ix_webhook_deliveries_claim", table_name="webhook_deliveries")
    op.drop_table("webhook_deliveries")
    op.drop_index("ix_event_recipients_event_order", table_name="event_recipients")
    op.drop_table("event_recipients")
    op.drop_table("webhook_endpoint_versions")
    op.drop_table("webhook_endpoints")
    # ### end Alembic commands ###
